"""
The twelve standardized employees and HCS-11 master data records.

Standardized against the People Code and feat/enhancing-agent-activities-v0 branch.
"""

from app.database.tables import (
    AcademicCycle,
    BenefitPlanRule,
    Dependent,
    Employee,
    ExpenseClaim,
    LeaveBalance,
    LeaveRequest,
    ManagerHistory,
    SchoolVerificationCase,
)

# HC-PC-002 §2.2.1. One entitlement, three pay rates, ninety days in total.
SICK_TRANCHES = (
    ("Sick leave (full pay)", 15, 100),
    ("Sick leave (half pay)", 45, 50),
    ("Sick leave (unpaid)", 30, 0),
)


def sick_leave_rows(days_used: int, year: int = 2026) -> list[LeaveBalance]:
    """The three tranche rows for an employee who has used `days_used` sick days."""
    rows, remaining_to_place = [], days_used
    for leave_type, entitled, pay_rate in SICK_TRANCHES:
        used = min(remaining_to_place, entitled)
        remaining_to_place -= used
        rows.append(
            LeaveBalance(
                leave_type=leave_type,
                entitled_days=entitled,
                used_days=used,
                remaining_days=entitled - used,
                carry_over_days=0,
                year=year,
                pay_rate_pct=pay_rate,
                accrued_days=float(entitled),
            )
        )
    return rows


def annual_leave_row(
    entitled: int,
    used: int,
    carry_over: int = 0,
    accrued: float | None = None,
    year: int = 2026,
) -> LeaveBalance:
    """One annual leave row with balance identity."""
    return LeaveBalance(
        leave_type="Annual leave",
        entitled_days=entitled,
        used_days=used,
        remaining_days=entitled + carry_over - used,
        carry_over_days=carry_over,
        year=year,
        pay_rate_pct=None,
        accrued_days=float(entitled) if accrued is None else accrued,
    )


def build_seed_employees() -> list[dict]:
    """Fresh, unattached records for the 12 standardized demonstration employees."""
    return [
        {
            # E0001 / EMP001: Alia Al Suwaidi (Senior Consultant)
            "employee": Employee(
                user_id="EMP001",
                payroll_id="P10001",
                name="Alia Al Suwaidi",
                name_ar="علياء السويدي",
                role="Senior Consultant",
                job_title="Senior Consultant",
                department="Strategy & Transformation",
                grade="Grade 8",
                employment_fraction=1.0,
                legal_entity="Demo Entity UAE",
                work_location="Abu Dhabi",
                benefit_plan_code="EDU_ENHANCED",
                preferred_language="Arabic",
                employment_status="Active",
                email="alia.suwaidi@hcservices.ae",
                phone="+971 50 123 4567",
                location="Abu Dhabi Office, Level 8",
                start_date="2021-03-14",
                years_of_service=5,
                probation_status="Passed",
                manager_name="Maitha Al Mazrouei",
                manager_id="EMP003",
                manager_email="maitha.mazrouei@hcservices.ae",
                manager_role="Executive Director",
            ),
            "balances": [
                annual_leave_row(entitled=24, used=12, carry_over=3),
                *sick_leave_rows(days_used=10),
                annual_leave_row(entitled=24, used=21, carry_over=0, year=2025),
            ],
            "manager_history": [
                ManagerHistory(
                    previous_manager="Rashid Al Ketbi",
                    current_manager="Maitha Al Mazrouei",
                    effective_date="2025-10-01",
                    change_reason="Promotion to Senior Consultant & Strategy realignment",
                ),
                ManagerHistory(
                    previous_manager="Initial Onboarding Manager",
                    current_manager="Rashid Al Ketbi",
                    effective_date="2021-03-14",
                    change_reason="Initial assignment upon joining Strategy team",
                ),
            ],
            "leave_requests": [
                LeaveRequest(
                    leave_type="Annual Leave",
                    start_date="2026-01-12",
                    end_date="2026-01-16",
                    days_requested=5,
                    status="Approved",
                    approver_name="Maitha Al Mazrouei",
                    notes="Winter holiday with family",
                ),
                LeaveRequest(
                    leave_type="Annual Leave",
                    start_date="2026-04-10",
                    end_date="2026-04-20",
                    days_requested=7,
                    status="Approved",
                    approver_name="Maitha Al Mazrouei",
                    notes="Spring break vacation",
                ),
                LeaveRequest(
                    leave_type="Sick Leave",
                    start_date="2026-07-02",
                    end_date="2026-07-13",
                    days_requested=10,
                    status="Approved",
                    approver_name="Maitha Al Mazrouei",
                    notes="Flu recovery with DHA medical certificate",
                ),
            ],
            "expense_claims": [
                ExpenseClaim(
                    category="Travel & Accommodation",
                    amount_aed=1200.00,
                    claim_date="2025-11-20",
                    status="Approved",
                    approver="Rashid Al Ketbi",
                    receipt_reference="REC-2025-1120",
                    description="Two nights, Abu Dhabi client engagement, AED 600 per night",
                    policy_reference="HC-PC-005 §5.3.3",
                ),
                ExpenseClaim(
                    category="Client Meals & Entertainment",
                    amount_aed=450.00,
                    claim_date="2026-05-14",
                    status="Approved",
                    approver="Maitha Al Mazrouei",
                    receipt_reference="REC-2026-0514",
                    description="Client dinner, 2 attendees including the employee, AED 225 per head",
                    policy_reference="HC-PC-005 §5.5.1",
                ),
                ExpenseClaim(
                    category="Local Travel & Taxi",
                    amount_aed=180.00,
                    claim_date="2026-06-20",
                    status="Approved",
                    approver="Maitha Al Mazrouei",
                    receipt_reference="REC-2026-0620",
                    description="Taxi fares, Dubai client site visits",
                    policy_reference="HC-PC-005 §5.3.4",
                ),
            ],
        },
        {
            # E0002 / EMP002: Rashid Al Ketbi (VP, Strategy & Operations)
            "employee": Employee(
                user_id="EMP002",
                payroll_id="P10002",
                name="Rashid Al Ketbi",
                name_ar="راشد الكتبي",
                role="VP, Strategy & Operations",
                job_title="VP, Strategy & Operations",
                department="Strategy & Transformation",
                grade="Grade 7",
                employment_fraction=1.0,
                legal_entity="Demo Entity UAE",
                work_location="Abu Dhabi",
                benefit_plan_code="EDU_STANDARD",
                preferred_language="Arabic",
                employment_status="Active",
                email="rashid.ketbi@hcservices.ae",
                phone="+971 50 234 5678",
                location="Abu Dhabi Office, Level 10",
                start_date="2022-07-01",
                years_of_service=4,
                probation_status="Passed",
                manager_name="Maitha Al Mazrouei",
                manager_id="EMP003",
                manager_email="maitha.mazrouei@hcservices.ae",
                manager_role="Executive Director",
            ),
            "balances": [
                annual_leave_row(entitled=24, used=6, carry_over=5),
                *sick_leave_rows(days_used=3),
                annual_leave_row(entitled=24, used=18, carry_over=0, year=2025),
            ],
            "manager_history": [
                ManagerHistory(
                    previous_manager="External Appointment",
                    current_manager="Maitha Al Mazrouei",
                    effective_date="2022-07-01",
                    change_reason="Appointment as VP, Strategy & Operations",
                ),
            ],
            "leave_requests": [
                LeaveRequest(
                    leave_type="Annual Leave",
                    start_date="2026-02-02",
                    end_date="2026-02-07",
                    days_requested=6,
                    status="Approved",
                    approver_name="Maitha Al Mazrouei",
                    notes="Family travel",
                ),
                LeaveRequest(
                    leave_type="Sick Leave",
                    start_date="2026-03-09",
                    end_date="2026-03-11",
                    days_requested=3,
                    status="Approved",
                    approver_name="Maitha Al Mazrouei",
                    notes="Certified medical absence",
                ),
            ],
            "expense_claims": [],
        },
        {
            # E0003 / EMP003: Maitha Al Mazrouei (Executive Director)
            "employee": Employee(
                user_id="EMP003",
                payroll_id="P10003",
                name="Maitha Al Mazrouei",
                name_ar="ميثاء المزروعي",
                role="Executive Director",
                job_title="Executive Director",
                department="Executive Leadership",
                grade="Grade 9",
                employment_fraction=1.0,
                legal_entity="Demo Services LLC",
                work_location="Dubai",
                benefit_plan_code="EDU_ENHANCED",
                preferred_language="English",
                employment_status="Active",
                email="maitha.mazrouei@hcservices.ae",
                phone="+971 50 345 6789",
                location="Dubai Office, Level 20",
                start_date="2019-11-10",
                years_of_service=7,
                probation_status="Passed",
                manager_name="Board of Directors",
                manager_id=None,
                manager_email="board@hcservices.ae",
                manager_role="Board of Directors",
            ),
            "balances": [
                annual_leave_row(entitled=26, used=15, carry_over=0),
                *sick_leave_rows(days_used=0),
                annual_leave_row(entitled=26, used=20, carry_over=0, year=2025),
            ],
            "manager_history": [],
            "leave_requests": [
                LeaveRequest(
                    leave_type="Annual Leave",
                    start_date="2026-07-06",
                    end_date="2026-07-24",
                    days_requested=15,
                    status="Approved",
                    approver_name="Board of Directors",
                    notes="Annual summer leave",
                ),
            ],
            "expense_claims": [],
        },
        {
            # E0004 / EMP004: Daniel Reed (Director, Finance & Treasury)
            "employee": Employee(
                user_id="EMP004",
                payroll_id="P10004",
                name="Daniel Reed",
                name_ar="دانيال ريد",
                role="Director, Finance & Treasury",
                job_title="Director, Finance & Treasury",
                department="Finance & Accounting",
                grade="Grade 6",
                employment_fraction=1.0,
                legal_entity="Demo Services LLC",
                work_location="Abu Dhabi",
                benefit_plan_code="EDU_STANDARD",
                preferred_language="English",
                employment_status="Active",
                email="daniel.reed@hcservices.ae",
                phone="+971 50 456 7890",
                location="Abu Dhabi Office, Level 6",
                start_date="2024-01-22",
                years_of_service=2,
                probation_status="Passed",
                manager_name="Maitha Al Mazrouei",
                manager_id="EMP003",
                manager_email="maitha.mazrouei@hcservices.ae",
                manager_role="Executive Director",
            ),
            "balances": [
                annual_leave_row(entitled=21, used=6, carry_over=0),
                *sick_leave_rows(days_used=0),
            ],
            "manager_history": [
                ManagerHistory(
                    previous_manager="External Appointment",
                    current_manager="Maitha Al Mazrouei",
                    effective_date="2024-01-22",
                    change_reason="Appointment as Director, Finance & Treasury",
                ),
            ],
            "leave_requests": [
                LeaveRequest(
                    leave_type="Annual Leave",
                    start_date="2026-03-16",
                    end_date="2026-03-23",
                    days_requested=6,
                    status="Approved",
                    approver_name="Maitha Al Mazrouei",
                    notes="Spring leave",
                ),
            ],
            "expense_claims": [
                ExpenseClaim(
                    category="Travel & Accommodation",
                    amount_aed=2850.00,
                    claim_date="2026-02-15",
                    status="Approved",
                    approver="Maitha Al Mazrouei",
                    receipt_reference="REC-2026-0215",
                    description="London, 3 nights at AED 950 per night, client engagement",
                    policy_reference="HC-PC-005 §5.3.3",
                ),
            ],
        },
        {
            # E0005 / EMP005: Noura Al Zaabi (Senior Specialist, On Leave)
            "employee": Employee(
                user_id="EMP005",
                payroll_id="P10005",
                name="Noura Al Zaabi",
                name_ar="نورة الزعابي",
                role="Senior Specialist, Regulatory Affairs",
                job_title="Senior Specialist, Regulatory Affairs",
                department="Legal & Compliance",
                grade="Grade 7",
                employment_fraction=1.0,
                legal_entity="Demo Entity UAE",
                work_location="Abu Dhabi",
                benefit_plan_code="EDU_STANDARD",
                preferred_language="Arabic",
                employment_status="On Leave",
                email="noura.zaabi@hcservices.ae",
                phone="+971 50 567 8901",
                location="Abu Dhabi Office, Level 7",
                start_date="2020-09-06",
                years_of_service=6,
                probation_status="Passed",
                manager_name="Maitha Al Mazrouei",
                manager_id="EMP003",
                manager_email="maitha.mazrouei@hcservices.ae",
                manager_role="Executive Director",
            ),
            "balances": [
                annual_leave_row(entitled=26, used=0, carry_over=0),
                *sick_leave_rows(days_used=0),
            ],
            "manager_history": [],
            "leave_requests": [],
            "expense_claims": [],
        },
        {
            # E0006 / EMP006: Sultan Al Neyadi (Manager, Client Delivery)
            "employee": Employee(
                user_id="EMP006",
                payroll_id="P10006",
                name="Sultan Al Neyadi",
                name_ar="سلطان النيادي",
                role="Manager, Client Delivery",
                job_title="Manager, Client Delivery",
                department="Client Delivery",
                grade="Grade 8",
                employment_fraction=1.0,
                legal_entity="Demo Entity UAE",
                work_location="Dubai",
                benefit_plan_code="EDU_ENHANCED",
                preferred_language="English",
                employment_status="Active",
                email="sultan.neyadi@hcservices.ae",
                phone="+971 50 678 9012",
                location="Dubai Office, Level 15",
                start_date="2018-05-17",
                years_of_service=8,
                probation_status="Passed",
                manager_name="Maitha Al Mazrouei",
                manager_id="EMP003",
                manager_email="maitha.mazrouei@hcservices.ae",
                manager_role="Executive Director",
            ),
            "balances": [
                annual_leave_row(entitled=26, used=8, carry_over=0),
                *sick_leave_rows(days_used=34),
                annual_leave_row(entitled=26, used=20, carry_over=0, year=2025),
            ],
            "manager_history": [
                ManagerHistory(
                    previous_manager="External Appointment",
                    current_manager="Maitha Al Mazrouei",
                    effective_date="2018-05-17",
                    change_reason="Appointment as Manager, Client Delivery",
                ),
            ],
            "leave_requests": [
                LeaveRequest(
                    leave_type="Annual Leave",
                    start_date="2026-05-04",
                    end_date="2026-05-13",
                    days_requested=8,
                    status="Approved",
                    approver_name="Maitha Al Mazrouei",
                    notes="Family leave",
                ),
                LeaveRequest(
                    leave_type="Sick Leave",
                    start_date="2026-02-02",
                    end_date="2026-02-13",
                    days_requested=10,
                    status="Approved",
                    approver_name="Maitha Al Mazrouei",
                    notes="Certified medical absence",
                ),
                LeaveRequest(
                    leave_type="Sick Leave",
                    start_date="2026-03-02",
                    end_date="2026-03-06",
                    days_requested=5,
                    status="Approved",
                    approver_name="Maitha Al Mazrouei",
                    notes="Certified medical absence",
                ),
                LeaveRequest(
                    leave_type="Sick Leave",
                    start_date="2026-04-13",
                    end_date="2026-04-24",
                    days_requested=10,
                    status="Approved",
                    approver_name="Maitha Al Mazrouei",
                    notes="Certified medical absence",
                ),
            ],
            "expense_claims": [
                ExpenseClaim(
                    category="Travel & Accommodation",
                    amount_aed=7600.00,
                    claim_date="2026-06-30",
                    status="Approved",
                    approver="Maitha Al Mazrouei",
                    receipt_reference="REC-2026-0630",
                    description="Riyadh client project delivery flights and accommodation",
                    policy_reference="HC-PC-005 §5.7.2",
                ),
            ],
        },
        {
            # E0007 / EMP007: Shamma Al Muhairi (Facilities Supervisor, Part-time, Probation)
            "employee": Employee(
                user_id="EMP007",
                payroll_id="P10007",
                name="Shamma Al Muhairi",
                name_ar="شما المهيري",
                role="Facilities Supervisor",
                job_title="Facilities Supervisor",
                department="Workplace & Facilities",
                grade="Grade 5",
                employment_fraction=0.6,
                legal_entity="Demo Services LLC",
                work_location="Abu Dhabi",
                benefit_plan_code="NONE",
                preferred_language="Arabic",
                employment_status="Active",
                email="shamma.muhairi@hcservices.ae",
                phone="+971 50 789 0123",
                location="Abu Dhabi Office, Ground Floor",
                start_date="2025-02-03",
                years_of_service=1,
                probation_status="Active",
                manager_name="Daniel Reed",
                manager_id="EMP004",
                manager_email="daniel.reed@hcservices.ae",
                manager_role="Director, Finance & Treasury",
            ),
            "balances": [
                annual_leave_row(entitled=14, used=4, carry_over=0, accrued=14.4),
                *sick_leave_rows(days_used=2),
            ],
            "manager_history": [
                ManagerHistory(
                    previous_manager="External Appointment",
                    current_manager="Daniel Reed",
                    effective_date="2025-02-03",
                    change_reason="Initial appointment to Workplace & Facilities",
                ),
            ],
            "leave_requests": [
                LeaveRequest(
                    leave_type="Annual Leave",
                    start_date="2026-04-06",
                    end_date="2026-04-09",
                    days_requested=4,
                    status="Approved",
                    approver_name="Daniel Reed",
                    notes="Personal leave",
                ),
            ],
            "expense_claims": [],
        },
        {
            # E0008 / EMP008: Tariq Al Balushi (Former Specialist, Terminated)
            "employee": Employee(
                user_id="EMP008",
                payroll_id="P10008",
                name="Tariq Al Balushi",
                name_ar="طارق البلوشي",
                role="Senior Strategy Specialist",
                job_title="Senior Strategy Specialist",
                department="Strategy & Transformation",
                grade="Grade 7",
                employment_fraction=1.0,
                legal_entity="Demo Entity UAE",
                work_location="Abu Dhabi",
                benefit_plan_code="EDU_STANDARD",
                preferred_language="Arabic",
                employment_status="Terminated",
                exit_date="2026-07-31",
                email="tariq.balushi@hcservices.ae",
                phone="+971 50 890 1234",
                location="Abu Dhabi Office, Level 10",
                start_date="2017-08-20",
                years_of_service=9,
                probation_status="Passed",
                manager_name="Maitha Al Mazrouei",
                manager_id="EMP003",
                manager_email="maitha.mazrouei@hcservices.ae",
                manager_role="Executive Director",
            ),
            "balances": [
                annual_leave_row(entitled=26, used=5, carry_over=0),
                *sick_leave_rows(days_used=0),
            ],
            "manager_history": [],
            "leave_requests": [
                LeaveRequest(
                    leave_type="Annual Leave",
                    start_date="2026-03-02",
                    end_date="2026-03-06",
                    days_requested=5,
                    status="Approved",
                    approver_name="Maitha Al Mazrouei",
                    notes="Personal leave",
                ),
            ],
            "expense_claims": [],
        },
        {
            # E0009 / EMP009: Elena Costa (VP, People & Culture)
            "employee": Employee(
                user_id="EMP009",
                payroll_id="P10009",
                name="Elena Costa",
                name_ar="إيلينا كوستا",
                role="VP, People & Culture",
                job_title="VP, People & Culture",
                department="People & Culture",
                grade="Grade 9",
                employment_fraction=1.0,
                legal_entity="Demo Services LLC",
                work_location="Dubai",
                benefit_plan_code="EDU_ENHANCED",
                preferred_language="English",
                employment_status="Active",
                email="elena.costa@hcservices.ae",
                phone="+971 50 901 2345",
                location="Dubai Office, Level 18",
                start_date="2023-04-12",
                years_of_service=3,
                probation_status="Passed",
                manager_name="Maitha Al Mazrouei",
                manager_id="EMP003",
                manager_email="maitha.mazrouei@hcservices.ae",
                manager_role="Executive Director",
            ),
            "balances": [
                annual_leave_row(entitled=24, used=7, carry_over=0),
                *sick_leave_rows(days_used=0),
            ],
            "manager_history": [],
            "leave_requests": [
                LeaveRequest(
                    leave_type="Annual Leave",
                    start_date="2026-04-10",
                    end_date="2026-04-20",
                    days_requested=7,
                    status="Approved",
                    approver_name="Maitha Al Mazrouei",
                    notes="Spring break",
                ),
            ],
            "expense_claims": [],
        },
        {
            # E0010 / EMP010: Khalifa Al Dhaheri (Associate Consultant)
            "employee": Employee(
                user_id="EMP010",
                payroll_id="P10010",
                name="Khalifa Al Dhaheri",
                name_ar="خليفة الظاهري",
                role="Associate Consultant",
                job_title="Associate Consultant",
                department="Digital & Technology",
                grade="Grade 6",
                employment_fraction=1.0,
                legal_entity="Demo Entity UAE",
                work_location="Abu Dhabi",
                benefit_plan_code="EDU_STANDARD",
                preferred_language="Arabic",
                employment_status="Active",
                email="khalifa.dhaheri@hcservices.ae",
                phone="+971 50 012 3456",
                location="Abu Dhabi Office, Level 5",
                start_date="2024-09-15",
                years_of_service=2,
                probation_status="Passed",
                manager_name="Alia Al Suwaidi",
                manager_id="EMP001",
                manager_email="alia.suwaidi@hcservices.ae",
                manager_role="Senior Consultant",
            ),
            "balances": [
                annual_leave_row(entitled=21, used=5, carry_over=0),
                *sick_leave_rows(days_used=0),
            ],
            "manager_history": [],
            "leave_requests": [
                LeaveRequest(
                    leave_type="Annual Leave",
                    start_date="2026-05-04",
                    end_date="2026-05-08",
                    days_requested=5,
                    status="Approved",
                    approver_name="Alia Al Suwaidi",
                    notes="Short break",
                ),
            ],
            "expense_claims": [],
        },
        {
            # E0011 / EMP011: Hessa Al Shamsi (Lead Consultant)
            "employee": Employee(
                user_id="EMP011",
                payroll_id="P10011",
                name="Hessa Al Shamsi",
                name_ar="حصة الشامسي",
                role="Lead Consultant",
                job_title="Lead Consultant",
                department="Strategy & Transformation",
                grade="Grade 8",
                employment_fraction=1.0,
                legal_entity="Demo Entity UAE",
                work_location="Abu Dhabi",
                benefit_plan_code="EDU_ENHANCED",
                preferred_language="English",
                employment_status="Active",
                email="hessa.shamsi@hcservices.ae",
                phone="+971 50 123 7890",
                location="Abu Dhabi Office, Level 11",
                start_date="2020-01-05",
                years_of_service=6,
                probation_status="Passed",
                manager_name="Alia Al Suwaidi",
                manager_id="EMP001",
                manager_email="alia.suwaidi@hcservices.ae",
                manager_role="Senior Consultant",
            ),
            "balances": [
                annual_leave_row(entitled=26, used=10, carry_over=0),
                *sick_leave_rows(days_used=0),
            ],
            "manager_history": [],
            "leave_requests": [
                LeaveRequest(
                    leave_type="Annual Leave",
                    start_date="2026-02-09",
                    end_date="2026-02-20",
                    days_requested=10,
                    status="Approved",
                    approver_name="Alia Al Suwaidi",
                    notes="Winter vacation",
                ),
                LeaveRequest(
                    leave_type="Annual Leave",
                    start_date="2026-10-05",
                    end_date="2026-10-16",
                    days_requested=10,
                    status="Pending",
                    approver_name="Alia Al Suwaidi",
                    notes="Awaiting line manager decision",
                ),
            ],
            "expense_claims": [],
        },
        {
            # E0012 / EMP012: Mohammed Al Marri (Associate Analyst)
            "employee": Employee(
                user_id="EMP012",
                payroll_id="P10012",
                name="Mohammed Al Marri",
                name_ar="محمد المري",
                role="Associate Analyst",
                job_title="Associate Analyst",
                department="Digital & Technology",
                grade="Grade 5",
                employment_fraction=1.0,
                legal_entity="Demo Services LLC",
                work_location="Dubai",
                benefit_plan_code="EDU_STANDARD",
                preferred_language="English",
                employment_status="Active",
                email="mohammed.marri@hcservices.ae",
                phone="+971 50 234 8901",
                location="Dubai Office, Level 12",
                start_date="2025-06-16",
                years_of_service=1,
                probation_status="Passed",
                manager_name="Alia Al Suwaidi",
                manager_id="EMP001",
                manager_email="alia.suwaidi@hcservices.ae",
                manager_role="Senior Consultant",
            ),
            "balances": [
                annual_leave_row(entitled=21, used=3, carry_over=0),
                *sick_leave_rows(days_used=0),
            ],
            "manager_history": [],
            "leave_requests": [
                LeaveRequest(
                    leave_type="Annual Leave",
                    start_date="2026-06-01",
                    end_date="2026-06-03",
                    days_requested=3,
                    status="Approved",
                    approver_name="Alia Al Suwaidi",
                    notes="Family leave",
                ),
            ],
            "expense_claims": [],
        },
    ]


def build_seed_hcs11_master_data() -> dict:
    """Master reference data for HCS-11: Plan Rules, Cycles, Dependents, and Verification Cases."""
    plan_rules = [
        BenefitPlanRule(
            plan_code="EDU_STANDARD",
            plan_name="Education Allowance – Standard",
            annual_limit_aed=25000,
            eligible_employee_statuses="Active | On Leave",
            eligible_relationship="Child",
            dependent_status_required="Active",
            school_enrolment_required="Enrolled",
            required_document_type="Proof of schooling",
            manual_review_conditions="Low extraction confidence | record mismatch | missing mandatory field",
            required_documents="enrolment_certificate | school_invoice | payment_receipt | employee_declaration",
            claimable_charges="tuition and academic instruction | registration and enrolment fees | examinations and assessments | school activities and enrichment",
            effective_start="2026-08-01",
            effective_end="2027-07-31",
            active_flag="Yes",
        ),
        BenefitPlanRule(
            plan_code="EDU_ENHANCED",
            plan_name="Education Allowance – Enhanced",
            annual_limit_aed=45000,
            eligible_employee_statuses="Active | On Leave",
            eligible_relationship="Child",
            dependent_status_required="Active",
            school_enrolment_required="Enrolled",
            required_document_type="Proof of schooling",
            manual_review_conditions="Low extraction confidence | record mismatch | missing mandatory field",
            required_documents="enrolment_certificate | school_invoice | payment_receipt | employee_declaration",
            claimable_charges="tuition and academic instruction | registration and enrolment fees | examinations and assessments | school activities and enrichment | books and learning materials",
            effective_start="2026-08-01",
            effective_end="2027-07-31",
            active_flag="Yes",
        ),
        BenefitPlanRule(
            plan_code="NONE",
            plan_name="No Education Allowance",
            annual_limit_aed=0,
            eligible_employee_statuses="Any",
            eligible_relationship="Not applicable",
            dependent_status_required="Not applicable",
            school_enrolment_required="Not applicable",
            required_document_type="Not applicable",
            manual_review_conditions="No automated approval; route unexpected submissions for review",
            required_documents=None,
            claimable_charges=None,
            effective_start="2026-08-01",
            effective_end="2027-07-31",
            active_flag="No",
        ),
    ]

    cycles = [
        AcademicCycle(
            cycle_id="AC2025-26",
            academic_year="2025–2026",
            cycle_status="Closed",
            submission_open_date="2025-08-01",
            submission_deadline="2025-10-15",
            review_deadline="2025-11-15",
            payroll_cutoff="2025-11-30",
            accepted_issue_start="2025-06-01",
            accepted_issue_end="2026-05-31",
        ),
        AcademicCycle(
            cycle_id="AC2026-27",
            academic_year="2026–2027",
            cycle_status="Open",
            submission_open_date="2026-08-01",
            submission_deadline="2026-10-15",
            review_deadline="2026-11-15",
            payroll_cutoff="2026-11-30",
            accepted_issue_start="2026-06-01",
            accepted_issue_end="2027-05-31",
        ),
    ]

    dependents = [
        Dependent(
            dependent_id="D0001",
            employee_id="EMP001",
            first_name="Zayed",
            last_name="Al Suwaidi",
            relationship_type="Child",
            date_of_birth="2015-02-11",
            dependent_status="Active",
            school_enrolment_status="Enrolled",
            preferred_language="Arabic",
        ),
        Dependent(
            dependent_id="D0002",
            employee_id="EMP001",
            first_name="Fatima",
            last_name="Al Suwaidi",
            relationship_type="Child",
            date_of_birth="2018-09-04",
            dependent_status="Active",
            school_enrolment_status="Enrolled",
            preferred_language="English",
        ),
        Dependent(
            dependent_id="D0003",
            employee_id="EMP001",
            first_name="Saif",
            last_name="Al Suwaidi",
            relationship_type="Spouse",
            date_of_birth="1987-06-23",
            dependent_status="Active",
            school_enrolment_status="Not Applicable",
            preferred_language="Arabic",
        ),
        Dependent(
            dependent_id="D0004",
            employee_id="EMP002",
            first_name="Hind",
            last_name="Al Ketbi",
            relationship_type="Child",
            date_of_birth="2013-12-17",
            dependent_status="Active",
            school_enrolment_status="Enrolled",
            preferred_language="Arabic",
        ),
        Dependent(
            dependent_id="D0005",
            employee_id="EMP002",
            first_name="Omar",
            last_name="Al Ketbi",
            relationship_type="Child",
            date_of_birth="2021-05-09",
            dependent_status="Active",
            school_enrolment_status="Not Enrolled",
            preferred_language="Arabic",
        ),
        Dependent(
            dependent_id="D0006",
            employee_id="EMP003",
            first_name="Saeed",
            last_name="Al Mazrouei",
            relationship_type="Child",
            date_of_birth="2011-08-30",
            dependent_status="Active",
            school_enrolment_status="Enrolled",
            preferred_language="English",
        ),
        Dependent(
            dependent_id="D0007",
            employee_id="EMP003",
            first_name="Dana",
            last_name="Al Mazrouei",
            relationship_type="Child",
            date_of_birth="2016-03-15",
            dependent_status="Active",
            school_enrolment_status="Enrolled",
            preferred_language="English",
        ),
        Dependent(
            dependent_id="D0008",
            employee_id="EMP004",
            first_name="Emma",
            last_name="Reed",
            relationship_type="Child",
            date_of_birth="2017-11-02",
            dependent_status="Active",
            school_enrolment_status="Enrolled",
            preferred_language="English",
        ),
        Dependent(
            dependent_id="D0009",
            employee_id="EMP005",
            first_name="Ali",
            last_name="Al Zaabi",
            relationship_type="Child",
            date_of_birth="2014-06-19",
            dependent_status="Active",
            school_enrolment_status="Enrolled",
            preferred_language="Arabic",
        ),
        Dependent(
            dependent_id="D0010",
            employee_id="EMP005",
            first_name="Latifa",
            last_name="Al Zaabi",
            relationship_type="Child",
            date_of_birth="2019-01-25",
            dependent_status="Inactive",
            school_enrolment_status="Enrolled",
            preferred_language="Arabic",
        ),
        Dependent(
            dependent_id="D0011",
            employee_id="EMP006",
            first_name="Shaikha",
            last_name="Al Neyadi",
            relationship_type="Child",
            date_of_birth="2012-04-07",
            dependent_status="Active",
            school_enrolment_status="Enrolled",
            preferred_language="English",
        ),
        Dependent(
            dependent_id="D0012",
            employee_id="EMP006",
            first_name="Hamdan",
            last_name="Al Neyadi",
            relationship_type="Child",
            date_of_birth="2017-07-28",
            dependent_status="Active",
            school_enrolment_status="Enrolled",
            preferred_language="English",
        ),
        Dependent(
            dependent_id="D0013",
            employee_id="EMP007",
            first_name="Salama",
            last_name="Al Muhairi",
            relationship_type="Child",
            date_of_birth="2016-10-13",
            dependent_status="Active",
            school_enrolment_status="Enrolled",
            preferred_language="Arabic",
        ),
        Dependent(
            dependent_id="D0014",
            employee_id="EMP008",
            first_name="Nayef",
            last_name="Al Balushi",
            relationship_type="Child",
            date_of_birth="2010-03-03",
            dependent_status="Active",
            school_enrolment_status="Enrolled",
            preferred_language="Arabic",
        ),
        Dependent(
            dependent_id="D0015",
            employee_id="EMP009",
            first_name="Luca",
            last_name="Costa",
            relationship_type="Child",
            date_of_birth="2015-05-21",
            dependent_status="Active",
            school_enrolment_status="Enrolled",
            preferred_language="English",
        ),
        Dependent(
            dependent_id="D0016",
            employee_id="EMP009",
            first_name="Sofia",
            last_name="Costa",
            relationship_type="Child",
            date_of_birth="2019-09-12",
            dependent_status="Active",
            school_enrolment_status="Enrolled",
            preferred_language="English",
        ),
        Dependent(
            dependent_id="D0017",
            employee_id="EMP010",
            first_name="Moza",
            last_name="Al Dhaheri",
            relationship_type="Child",
            date_of_birth="2018-02-14",
            dependent_status="Active",
            school_enrolment_status="Enrolled",
            preferred_language="Arabic",
        ),
        Dependent(
            dependent_id="D0018",
            employee_id="EMP011",
            first_name="Mariam",
            last_name="Al Shamsi",
            relationship_type="Child",
            date_of_birth="2014-11-26",
            dependent_status="Active",
            school_enrolment_status="Enrolled",
            preferred_language="English",
        ),
        Dependent(
            dependent_id="D0019",
            employee_id="EMP011",
            first_name="Khalid",
            last_name="Al Shamsi",
            relationship_type="Child",
            date_of_birth="2020-08-08",
            dependent_status="Active",
            school_enrolment_status="Enrolled",
            preferred_language="English",
        ),
        Dependent(
            dependent_id="D0020",
            employee_id="EMP012",
            first_name="Amna",
            last_name="Al Marri",
            relationship_type="Child",
            date_of_birth="2017-04-18",
            dependent_status="Active",
            school_enrolment_status="Enrolled",
            preferred_language="English",
        ),
    ]

    cases = [
        SchoolVerificationCase(
            case_id="CASE0001",
            employee_id="EMP001",
            dependent_id="D0001",
            cycle_id="AC2026-27",
            case_status="Submitted",
            submission_deadline="2026-10-15",
            reminder_count=0,
            document_reference="docs/CASE0001/proof_of_schooling.pdf",
            extraction_status="Pending",
            matching_status="Not Started",
            rules_check_status="Not Started",
            human_review_status="Not Required",
            final_outcome="Not Evaluated",
            payment_status="Not Ready",
            notes="Document received; extraction queued",
        ),
        SchoolVerificationCase(
            case_id="CASE0002",
            employee_id="EMP001",
            dependent_id="D0002",
            cycle_id="AC2026-27",
            case_status="Awaiting Submission",
            submission_deadline="2026-10-15",
            reminder_count=1,
            document_reference=None,
            extraction_status="Not Started",
            matching_status="Not Started",
            rules_check_status="Not Started",
            human_review_status="Not Required",
            final_outcome="Not Evaluated",
            payment_status="Not Ready",
            notes="First reminder sent",
        ),
        SchoolVerificationCase(
            case_id="CASE0003",
            employee_id="EMP002",
            dependent_id="D0004",
            cycle_id="AC2026-27",
            case_status="Under Extraction",
            submission_deadline="2026-10-15",
            reminder_count=0,
            document_reference="docs/CASE0003/proof_of_schooling.pdf",
            extraction_status="Completed",
            matching_status="Pending",
            rules_check_status="Not Started",
            human_review_status="Not Required",
            final_outcome="Not Evaluated",
            payment_status="Not Ready",
            notes="Extracted fields awaiting entity match",
        ),
        SchoolVerificationCase(
            case_id="CASE0004",
            employee_id="EMP002",
            dependent_id="D0005",
            cycle_id="AC2026-27",
            case_status="Exception Review",
            submission_deadline="2026-10-15",
            reminder_count=0,
            document_reference="docs/CASE0004/proof_of_schooling.pdf",
            extraction_status="Completed",
            matching_status="Needs Review",
            rules_check_status="Not Started",
            human_review_status="Pending",
            final_outcome="Not Evaluated",
            payment_status="Not Ready",
            assigned_reviewer="Reviewer A",
            notes="School enrolment conflicts with dependent master data",
        ),
        SchoolVerificationCase(
            case_id="CASE0005",
            employee_id="EMP003",
            dependent_id="D0006",
            cycle_id="AC2026-27",
            case_status="Under Review",
            submission_deadline="2026-10-15",
            reminder_count=0,
            document_reference="docs/CASE0005/proof_of_schooling.pdf",
            extraction_status="Completed",
            matching_status="Matched",
            rules_check_status="Pending",
            human_review_status="Not Required",
            final_outcome="Not Evaluated",
            payment_status="Not Ready",
            notes="Rules evaluation queued",
        ),
        SchoolVerificationCase(
            case_id="CASE0006",
            employee_id="EMP003",
            dependent_id="D0007",
            cycle_id="AC2026-27",
            case_status="Submitted",
            submission_deadline="2026-10-15",
            reminder_count=0,
            document_reference="docs/CASE0006/proof_of_schooling_ar.pdf",
            extraction_status="Pending",
            matching_status="Not Started",
            rules_check_status="Not Started",
            human_review_status="Not Required",
            final_outcome="Not Evaluated",
            payment_status="Not Ready",
            notes="Arabic sample document",
        ),
        SchoolVerificationCase(
            case_id="CASE0007",
            employee_id="EMP004",
            dependent_id="D0008",
            cycle_id="AC2026-27",
            case_status="Awaiting Submission",
            submission_deadline="2026-10-15",
            reminder_count=2,
            document_reference=None,
            extraction_status="Not Started",
            matching_status="Not Started",
            rules_check_status="Not Started",
            human_review_status="Not Required",
            final_outcome="Not Evaluated",
            payment_status="Not Ready",
            notes="Second reminder due",
        ),
        SchoolVerificationCase(
            case_id="CASE0008",
            employee_id="EMP005",
            dependent_id="D0009",
            cycle_id="AC2026-27",
            case_status="Under Review",
            submission_deadline="2026-10-15",
            reminder_count=0,
            document_reference="docs/CASE0008/proof_of_schooling.pdf",
            extraction_status="Completed",
            matching_status="Matched",
            rules_check_status="Pending",
            human_review_status="Not Required",
            final_outcome="Not Evaluated",
            payment_status="Not Ready",
            notes="Employee is on leave; apply approved policy rule",
        ),
        SchoolVerificationCase(
            case_id="CASE0009",
            employee_id="EMP006",
            dependent_id="D0011",
            cycle_id="AC2026-27",
            case_status="Under Extraction",
            submission_deadline="2026-10-15",
            reminder_count=0,
            document_reference="docs/CASE0009/proof_of_schooling.pdf",
            extraction_status="Pending",
            matching_status="Not Started",
            rules_check_status="Not Started",
            human_review_status="Not Required",
            final_outcome="Not Evaluated",
            payment_status="Not Ready",
            notes="Extraction queued",
        ),
        SchoolVerificationCase(
            case_id="CASE0010",
            employee_id="EMP009",
            dependent_id="D0015",
            cycle_id="AC2026-27",
            case_status="Submitted",
            submission_deadline="2026-10-15",
            reminder_count=0,
            document_reference="docs/CASE0010/proof_of_schooling.pdf",
            extraction_status="Pending",
            matching_status="Not Started",
            rules_check_status="Not Started",
            human_review_status="Not Required",
            final_outcome="Not Evaluated",
            payment_status="Not Ready",
            notes="Document received",
        ),
        SchoolVerificationCase(
            case_id="CASE0011",
            employee_id="EMP010",
            dependent_id="D0017",
            cycle_id="AC2026-27",
            case_status="Exception Review",
            submission_deadline="2026-10-15",
            reminder_count=0,
            document_reference="docs/CASE0011/proof_of_schooling.pdf",
            extraction_status="Completed",
            matching_status="Needs Review",
            rules_check_status="Not Started",
            human_review_status="Pending",
            final_outcome="Not Evaluated",
            payment_status="Not Ready",
            assigned_reviewer="Reviewer B",
            notes="Name variation requires human confirmation",
        ),
        SchoolVerificationCase(
            case_id="CASE0012",
            employee_id="EMP011",
            dependent_id="D0018",
            cycle_id="AC2026-27",
            case_status="Awaiting Submission",
            submission_deadline="2026-10-15",
            reminder_count=0,
            document_reference=None,
            extraction_status="Not Started",
            matching_status="Not Started",
            rules_check_status="Not Started",
            human_review_status="Not Required",
            final_outcome="Not Evaluated",
            payment_status="Not Ready",
            notes="Initial request scheduled",
        ),
    ]

    return {
        "plan_rules": plan_rules,
        "cycles": cycles,
        "dependents": dependents,
        "cases": cases,
    }
